version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  camunda:
    image: datakurre/plone-camunda:latest
    restart: always
    ports:
      - 8081:8081
      - 5005:5005
    environment:
      - MICRONAUT_SERVER_HOST=0.0.0.0
      - MICRONAUT_SERVER_PORT=8081
      - DATASOURCES_DEFAULT_URL=jdbc:postgresql://db:5432/postgres
      - PLONE_PUBLIC_KEY=/var/lib/plone-jwt-signing-key.pub
      - MAIL_CONFIG=/var/lib/camunda-mail-config.ini
    command: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    volumes:
      - ./ec-ed25519-pub-key.pem:/var/lib/plone-jwt-signing-key.pub:Z
      - ./docker-compose-mail-config.ini:/var/lib/camunda-mail-config.ini:Z

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
