[project]
name = "bpmproxy-editor-bot"
version = "0.1.0"
description = "Purjo Robot Framework tasks for the BPM proxy editor example"
requires-python = ">=3.10"
dependencies = [
    "robotframework>=7.4b2",
    "rpaframework-openai>=1.1.2",
]

[tool.purjo.topics."GPT Create Article"]
name = "Create draft"
on-fail = "ERROR"
process-variables = true

[tool.purjo.topics."GPT Iterate Article"]
name = "Iterate draft"
on-fail = "ERROR"
process-variables = true

[tool.purjo.topics."GPT Create Titles"]
name = "Create title"
on-fail = "ERROR"
process-variables = true

[tool.purjo.topics."GPT Create Description"]
name = "Create description"
on-fail = "ERROR"
process-variables = true

[tool.purjo.topics."GPT Create Keywords"]
name = "Create keywords"
on-fail = "ERROR"
process-variables = true

[tool.purjo.topics."GPT Create Image"]
name = "Create image"
on-fail = "ERROR"
process-variables = true

[tool.purjo.secrets.default]
provider = "file"
path = "secrets.json"
