"""operaton-tasks worker for the review process "Plone Workflow Transition" topic.

Listens for "Plone Workflow Transition" tasks generated by the review process,
resolves the Plone content item by UUID, aggregates all individual and coordinator
review comments, and submits the workflow transition (publish or reject) with the
complete review submitted as the transition comment.

Run with:
    uv run --env-file secrets.env --with="operaton-tasks[cli]" operaton-tasks serve tasks.py
or:
    make serve
"""

import json
import os
from typing import Any

import aiohttp
import operaton.tasks
from operaton.tasks.types import (
    CompleteExternalTaskDto,
    ExternalTaskComplete,
    LockedExternalTaskDto,
)

PLONE_URL = os.environ.get("PLONE_URL", "http://localhost:8080/Plone")
PLONE_AUTHORIZATION = os.environ.get("PLONE_AUTHORIZATION", "")


def format_review_comment(variables: dict[str, Any]) -> str:
    """Format combined reviewer feedback and coordinator comment for workflow history."""
    sections: list[str] = []

    # Individual reviews
    reviews_var = variables.get("reviews")
    if reviews_var is not None and getattr(reviews_var, "value", None):
        val = reviews_var.value
        if isinstance(val, str) and val.strip():
            try:
                val = json.loads(val)
            except ValueError:
                pass
        if isinstance(val, list):
            sections.append(
                "### Reviewer Feedback:\n"
                + "\n".join(f"- {item}" for item in val if item)
            )
        elif isinstance(val, str) and val.strip():
            sections.append(f"### Reviewer Feedback:\n{val}")
    elif "reviewSummary" in variables and getattr(
        variables["reviewSummary"], "value", None
    ):
        summary = str(variables["reviewSummary"].value).strip()
        if summary:
            sections.append(f"### Reviewer Feedback:\n{summary}")

    # Main reviewer / coordinator note
    main_note_var = variables.get("mainReviewerComment")
    if main_note_var is not None and getattr(main_note_var, "value", None):
        note = str(main_note_var.value).strip()
        if note:
            sections.append(f"### Coordinator Decision Note:\n{note}")

    return "\n\n".join(sections).strip()


@operaton.tasks.task("Plone Workflow Transition")
async def transition_content(task: LockedExternalTaskDto) -> ExternalTaskComplete:
    """Resolve Plone content UUID and execute the requested workflow transition with review comment."""
    variables = task.variables or {}
    try:
        uuid = variables["uuid"].value
        transition = variables["transition"].value
    except KeyError as exc:
        raise RuntimeError(f"Missing required process variable: {exc}") from exc

    comment = format_review_comment(variables)

    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    if PLONE_AUTHORIZATION:
        headers["Authorization"] = PLONE_AUTHORIZATION

    async with aiohttp.ClientSession() as http:
        async with http.get(
            f"{PLONE_URL}/resolveuid/{uuid}",
            headers=headers,
            allow_redirects=False,
        ) as resolved:
            if resolved.status != 301:
                raise RuntimeError(
                    f"Expected a redirect resolving {uuid}, got {resolved.status}."
                )
            url = resolved.headers["Location"]

        payload: dict[str, Any] = {}
        if comment:
            payload["comment"] = comment

        async with http.post(
            f"{url}/@workflow/{transition}", headers=headers, json=payload
        ) as response:
            if response.status != 200:
                raise RuntimeError(
                    f"Workflow transition {transition!r} on {url} failed: "
                    f"{response.status} {await response.text()}"
                )

    return ExternalTaskComplete(
        task=task,
        response=CompleteExternalTaskDto(workerId=task.workerId),
    )
